# Generated by Django 3.0.3 on 2020-10-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderIten',
            new_name='OrderItem',
        ),
    ]
